
services:
  app-1:
    container_name: app-1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  jenkins-master:
    container_name: jenkins-master
    build:
      context: jenkins
      dockerfile: Dockerfile
    ports:
      - "8080:8080"       # UI de Jenkins
      - "50000:50000"     # Puerto de comunicación con agentes
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
