services:
  agent-4:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-4
    user: root
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock