services:
  agent-2:
    build:
      context: .
      dockerfile: Dockerfile   # tu Dockerfile.agent-2
    container_name: agent-2
    user: root                # <- así el agente corre como root
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock