services:
  agent-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agent-3
    user: root
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock